Welcome to Debian GNU/Linux PowerPC (CODENAME)

You have the choice of installing your system using one of two
different versions, 'debian' or 'debian24'.

The 'debian' option is the default; it uses version 2.2 of the Linux
kernel and is proven to be stable on most hardware.  The 'debian24'
option is based on the 2.4 Linux kernel, and is a bit more
cutting-edge, but it has better support for newer hardware.  If you
have a Power Macintosh computer manufactured within the last six
months, definitely choose 'debian24'.

Additionally, there are 'debian-safe' and 'debian24-safe' options
which you should try if the system fails to boot at all (the typical
symptom is a white screen which doesn't go away).

************************************
If in doubt, just choose 'debian', and if that doesn't work, try
'debian24', 'debian-safe', and 'debian24-safe' in that order.
************************************
