Welcome to Debian GNU/Linux ${DEBIAN_VERSION}!

This is a Debian installation ${MEDIA_TYPE},
built on ${BUILD_DATE}.


Enter one of the following options to begin:

install     64-bit processor (G5 or POWER3/4/5/6/7)
install32   32-bit processor (G4 or earlier)

Press TAB for a full list of options.


If the system fails to boot with a white screen
which doesn't go away, add 'video=ofonly'.

The following desktop environments are available:
gnome, kde, xfce and lxde.  The default is ${DEFAULT_DESKTOP}.
If you prefer a different one, append
    "desktop=<your choice>"
e.g. to do an expert install with the xfce desktop
environment, type
    "expert desktop=xfce"
at the "boot:" prompt.


