Welcome to Debian GNU/Linux ${DEBIAN_VERSION}!

This is a Debian installation ${MEDIA_TYPE},
built on ${BUILD_DATE}.

In addition to the default 'install' option, 
there is 'install-safe' which you should try if 
the system fails to boot at all (the typical
symptom is a white screen which doesn't go away).

For maximum control, you can use the 'expert'
and 'expert-safe' options.

The plain options are for the powerpc family of
processors (from 601 to G4). The -power3 options
are for IBM Power3 boxes, and the -power4 options
are for IBM Power4 and Apple G5 boxes.

************************************
If in doubt, just choose 'install', and if that 
doesn't work, try 'install-safe'.
************************************
