#!/bin/bash

# Example script to use with slink_cd - this will create trees for
# i386, m68k, sparc and alpha. 
# (c) Steve McIntyre 11 Feb 1999, released under GPL

for ARCH in m68k i386 alpha sparc
do
        echo TDIR=/debian/local/slinkcd-$ARCH OUT=/debian/local/OUT-$ARCH \
		MIRROR=/debian NONUS=/debian/Debian-non-US \
		./slink_cd \
		clean genlist tree flatten md5check packages boot \
		extras $ARCH md5list images imagesums

        TDIR=/debian/local/slinkcd-$ARCH OUT=/debian/local/OUT-$ARCH \
		MIRROR=/debian NONUS=/debian/Debian-non-US \
		BOOTDIR=/usr/lib/silo \
		./slink_cd \
		clean genlist tree flatten md5check packages boot \
		extras $ARCH md5list images imagesums
done


