#!/bin/bash
#
# boot-powerpc v 1.13 (c) Steve McIntyre <stevem@chiark.greenend.org.uk>,
# Chris Lawrence <lawrencc@debian.org>, Christian Steigies <cts@debian.org>, 
# Michael Schmitz <MSchmitz@lbl.gov>, Hartmut Koptein <koptein@debian.org>
# Released under GPL 31 Mar 1999
# See the file COPYING for license details
# Released as part of the slink_cd package, not much use standalone
#
# Do install stuff for powerpc, including making bootable CDs
#
# $1 is Debian-mirror location
# $2 is start directory location (where the scripts live)
# $3 is tmpdir location
# $4 is the binary arch
# $5 is debug level
# $6 is $BOOTDIR
#
# If you're burning a CD, use the mkhybrid in potato (HFS is broken in the
# slink version of mkhybrid; at least it is for me).  Please don't use Joliet
# extensions; some Mac kernels have apparently been known to choke on them
# (and you really shouldn't be supporting a Microsoft Standard anyway :-)
#

MIRROR=$1
BASEDIR=$2
TDIR=$3
ARCH=$4
VERBOSE=$5
BOOTDIR=$6

. $BASEDIR/vecho # Include local definitions for vecho, vvecho, vvvecho

DISKSROOT="$MIRROR/dists/potato/main/disks-powerpc/current"
CDROOT="$TDIR/potato1"
INSTALLDIR="$CDROOT/install"

cd $INSTALLDIR

# Debian/PowerPC consits currently for three parts: CHRP, PMac and PReP

######### CHRP - Stuff ######################
vecho Installing CHRP files
tar -C .. -zxf $DISKSROOT/chrp/chrpinstall.tar.gz
mv debian chrp
cp $DISKSROOT/chrp/* chrp

########## PMac - Stuff #####################
vecho Installing Power-Macintosh files
tar -C .. -xzf $DISKSROOT/pmac/install.tar.gz
mv debian pmac
cp $DISKSROOT/pmac/* pmac

########## PReP - Stuff #####################
vecho Installing PReP files
tar -C .. -zxf $DISKSROOT/source/prepinstall.tar.gz
mv debian prep
cp $DISKSROOT/prep/* prep

####### fix a few things up... ##############
vecho Installing PowerPC FAQ and tools
mkdir common
mv basecont.txt.info common
mv ../README.info ../README.powerpc.info
cp ../README.1ST.info ../README.multicd.info

cd $CDROOT
vecho Extracting $BASEDIR/pmacinstall-cd.tar.gz instead.
tar xzf $BASEDIR/pmacinstall-cd.tar.gz

