#!/bin/bash
#
# boot-powerpc v 1.13 (c) Steve McIntyre <stevem@chiark.greenend.org.uk>,
# Chris Lawrence <lawrencc@debian.org>, Christian Steigies <cts@debian.org>, 
# Michael Schmitz <MSchmitz@lbl.gov>
# Released under GPL 31 Mar 1999
# See the file COPYING for license details
# Released as part of the slink_cd package, not much use standalone
#
# Do install stuff for sparc, including making bootable CDs
#
# $1 is Debian-mirror location
# $2 is start directory location (where the scripts live)
# $3 is tmpdir location
# $4 is the binary arch
# $5 is debug level
# $6 is $BOOTDIR
#
# Enjoy!  This is all completely free.
# - Chris Lawrence <lawrencc@debian.org>
#
# Rewritten by Steve McIntyre <stevem@chiark.greenend.org.uk> in sh to
# interface better with the slink_cd package and cope with the mirror
# layout, 28 Feb 1999.
# Hopefully this will do the same job as the python map stuff did, it
# appears to...
#
# If you're burning a CD, use the mkhybrid in potato (HFS is broken in the
# slink version of mkhybrid; at least it is for me).  Please don't use Joliet
# extensions; some Mac kernels have apparently been known to choke on them
# (and you really shouldn't be supporting a Microsoft Standard anyway :-)
#
# You may also want the following:
# * A copy of the Linux/powerpc FAQ
# * A copy of my powerpc-specific README and powerpc-tools directories
# * The powerpc kernel sources from sunsite.auc.dk:/projects/680x0
#   (Sunsite-Denmark is rsync-capable at sunsite.auc.dk::ftp)
#   I recommend getting the 2.0.36 and 2.2.1-pre2 sources at least.
#   (Actually 2.0.36 is non-essential since it's on the CDs already;
#    you probably DO want the 2.2.1-pre2 tree however [under v2.1!]).
#
# MVME/BVME users will love you if you also include the "tools" directory
# from the FTP site, since they may want/need rawwrite for MS-DOS.
#
# The first two items are in a tar file at master.debian.org:~lawrencc, along
# with a silly rsync script that will accomplish the last item.

MIRROR=$1
BASEDIR=$2
TDIR=$3
ARCH=$4
VERBOSE=$5
BOOTDIR=$6

. $BASEDIR/vecho # Include local definitions for vecho, vvecho, vvvecho

DISKSROOT="$MIRROR/dists/potato/main/disks-powerpc/current"
CDROOT="$TDIR/potato1"
INSTALLDIR="$CDROOT/install"

cd $INSTALLDIR

vecho Installing CHRP files
tar -C .. -zxf $DISKSROOT/chrp/chrpinstall.lha
mv debian chrp
mv debian.info chrp.info
cp $DISKSROOT/chrp/* chrp

# Needs to be executable
#chmod a+x chrp/amiboot-5.6

# Add .info files for chrp
tar -C .. -xzf $BASEDIR/cts_chrp_info.tar.gz
for file in `tar tzf $BASEDIR/cts_chrp_info.tar.gz`
do
	chmod a+r ../$file
done
# And fix a few things up...
mkdir common
mv basecont.txt.info common
mv ../README.info ../README.powerpc.info
cp ../README.1ST.info ../README.multicd.info

vecho Installing Power-Macintosh files
lha xqf $DISKSROOT/pmac/install.lzh
mv debian pmac
cp $DISKSROOT/pmac/* pmac

vecho hexbin PReP files
cd $INSTALLDIR/prep
hexbin *.hqx

vecho Installing PReP files
tar -C .. -zxf $DISKSROOT/source/prepinstall.tar.gz
cp $DISKSROOT/prep/* prep

vecho Installing powerpc FAQ and tools
mkdir $CDROOT/tmp
cd $CDROOT/tmp
tar xzf $BASEDIR/powerpc-cd-misc.tar.gz
mv powerpc-faq powerpc-tools ..
mv update-kernels ../update-kernels.powerpc
cd ..
rm -rf tmp

cd $CDROOT
# make mountpoint and temp HFS filesystem image
rm -rf /var/tmp/mnt-pmacinstall
mkdir /var/tmp/mnt-pmacinstall
dd if=/dev/zero of=/var/tmp/pmacinstall-temp.img bs=1024 count=1440
hformat /var/tmp/pmacinstall-temp.img
# mount it (':' is top dir) using hfsutils
hmount /var/tmp/pmacinstall-temp.img
# copy booter and preferences files in place (color table missing but 
# Penguin-17 has colors fixed anyway
###hcopy -b install/mac/Penguin-17.hqx :
###hcopy -b install/mac/Penguin_Prefs.hqx :"Penguin Prefs"
###hcopy -b "install/mac/Penguin_Prefs_(autoboot).hqx" :"Penguin Prefs (autoboot)"
# unmount HFS image
humount /var/tmp/pmacinstall-temp.img
# mount this HFS floppy image again as netatalk using the loopback mount command
if [ ! 'mount -t hfs -o loop,fork=netatalk,afpd /var/tmp/pmacinstall-temp.img /var/tmp/mnt-pmacinstall' ] ; then
	# We managed to mount it loop-back
	# copy over both Penguin-15 and .AppleDouble/Penguin-15
	# copy over both Penguin Prefs and .AppleDouble/Penguin Prefs
	# (.AppleDouble files go into .AppleDouble subdir of target dir)
	cp /var/tmp/mnt-pmacinstall/Penguin* install/pmac/
	mkdir install/mac/.AppleDouble
	cp /var/tmp/mnt-macinstall/.AppleDouble/Penguin* install/pmac/.AppleDouble/
	# unmount, cleanup
	umount /var/tmp/mnt-pmacinstall
	rm /var/tmp/pmacinstall-temp.img
	rmdir /var/tmp/mnt-pmacinstall
else
	# We failed to mount it. Use the fallback tar.gz that we have
	vecho HFS loopback mount failed on /var/tmp/macinstall-temp.img
	vecho This is not fatal, but check that you have permissions to do this
    vecho and that you have HFS support in your kernel...
	vecho Extracting $BASEDIR/pmacinstall-cd.tar.gz instead.
	tar xzf $BASEDIR/pmacinstall-cd.tar.gz
fi

#
# can remove the .hqx stuff now I guess. 
#
# make CD image using the command
# mkhybrid -map <mapfile> --netatalk -a -j -hfs -r -V <label> -o <image> <source dir>
#
# map file contains stuff like
# # ext. xlate  creator  type    comment
# .hqx   Ascii  'BnHx'   'TEXT'  "BinHex file"
# .mov   Raw    'TVOD'   'MooV'  "QuickTime Movie"
# .deb   Raw    'Debn'   'bina'  "Debian package"
# .bin   Raw    'Debn'   'bina'  "Floppy or ramdisk image"
# *      Ascii  'ttxt'   'TEXT'  "Text file"
#
# Note that we can't use MacBinary mapping for .bin files due to
# name clashes with the binary image files, so we have to provide 
# all encoded Mac files in BinHex format.
#
# Kudos Brad Midgley, <brad@pht.com> for the tricks!
#
# Possible alternative: convert .hqx in MacBinary files, but we'd need
# to use a different extension as .bin is taken by the disk images.
# i.e. hexbin -s Penguin-17.hqx > Penguin-17.mac
# and use .mac as MacBinary extension. I don't know offhand what the 
# creator/type for MacBinary is. --netatalk would be replaced by 
# --macbin, possibly together with --probe.


 
