#!/bin/bash
#
# Do install stuff for alpha, including making bootable CDs
# Works with debian-installer
#
#Vorlon:
#
#The following pieces are still missing:
#
#- MILO bootloader & images.  I have no way to test this directly, and
#  haven't used MILO for years, so I'm giving this a pass on the first
#  run.
#- Floppy images.  Currently, debian-installer claims not to support
#  the floppy target on alpha, which is arbitrary, but there may just not
#  be any reason to continue supporting this install method.  Another
#  decision that can be made later.
#
# $1 is the CD number
# $2 is the temporary CD build dir

. $BASEDIR/tools/boot/$CODENAME/common.sh

set -e

N=$1
CDDIR=$2
BOOTDIR=

cd $CDDIR/..

#
# This script is called with $1 (now $N) as the CD to 
# make bootable.  N may be in the form "n" or "n_NONUS"
# There may be more than 4 disks...support extras.

# Strip NONUS part of disk number
# NN will be 1...N so it can be used as an index
#
NN=`echo $N | sed -e 's/_NONUS//'`

# Download boot images
# XXX: Driver floppies?  Any alpha that /has/ a CDROM should be able to
# boot from it, so this would be pure convenience of distribution.
#for image in cd_drivers-image.img cdrom-image.img cdrom-initrd.gz floppy-image.img floppy-initrd.gz net_drivers-image.img netboot-initrd.gz vmlinuz ; do

for image in bootlx cdrom-initrd.gz cdrom-linux; do
    if [ ! -e "$image" ]; then
	# XXX: not really 'daily'...
	wget -q http://people.debian.org/~vorlon/d-i/images/daily/$image
    fi
done

if [ $NN = 1 ]; then
    echo "Using $THISTYPE boot-disks image on CD$N"
    mkdir -p boot$N/boot
    cp bootlx cdrom-initrd.gz cdrom-linux boot$N/boot/

    mkdir -p boot$N/etc
    cat <<EOF > boot$N/etc/aboot.conf
0:boot/cdrom-linux ramdisk_size=16384 initrd=/boot/cdrom-initrd.gz root=/dev/rd/0 devfs=mount,dall
1:boot/cdrom-linux ramdisk_size=16384 initrd=/boot/cdrom-initrd.gz root=/dev/rd/0 devfs=mount,dall console=ttyS0
2:boot/cdrom-linux ramdisk_size=16384 initrd=/boot/cdrom-initrd.gz root=/dev/rd/0 devfs=mount,dall console=ttyS1
EOF

    echo -n "-cache-inodes -J -l "  > $N.mkisofs_opts
    mkdir -p boot$N/milo
    # XXX: we need to build milo first.
    #cp linload.exe ldmilo.exe boot$N/milo
    #cp -f $(ls MILO/milo_*.bin | sed 's,\(.*\)milo_\(.*\).bin,\1\2,') \
    #     boot$N/milo/

    # XXX: populate the install directory as well, if we want floppies.
    #cp -lf *.img $CDDIR/install
    #cp -lf floppy-initrd.gz $CDDIR/install

    # write final lines to mkisofs_opts
    echo -n "boot$N " >> $N.mkisofs_opts

else
    mkdir boot$N
    echo -n "-cache-inodes -J -l "  > $N.mkisofs_opts
fi

#install_languages $CDDIR
