#!/bin/bash
#
# boot-i386 v 1.13 (c) Steve McIntyre <stevem@chiark.greenend.org.uk>
# Released under GPL 31 Mar 1999
# 06-10-99 jjw Added $CODENAME and $CODENAME_STATUS support 
#
# Heavily hacked by Raphaël Hertzog <hertzog@debian.org> for
# YACS (the new debian-cd in potato)
# 12MAR00  updated for current i386 bootdisks  --jwest
#
# Do install stuff for i386, including making bootable CDs
#
# $1 is the CD number
# $2 is the temporary CD build dir
# CODENAME1 used temporarly to point to potato boot disks -- jwest

set -e

N=$1
CDDIR=$2
BOOTDIR=
# set bootdisks to potato for the moment.
CODENAME1=potato

cd $CDDIR/..

# Compact image for disk 2
if [ $N == 2 ]; then
	:> 2.mkisofs_opts
	if [ -e $MIRROR/dists/$CODENAME1/main/disks-$ARCH/current/images-2.88/compact/rescue.bin ] 
	then
	  mkdir -p boot2/boot
	  cp $MIRROR/dists/$CODENAME1/main/disks-$ARCH/current/images-2.88/compact/rescue.bin boot2/boot/
	  echo -n "-J -b boot/rescue.bin -c boot/boot.catalog boot2" \
		        > 2.mkisofs_opts
	fi
	exit 0;
fi

# Disks != 1 and not 2
if [ $N != 1 ]; then 
	echo -n "-J" > $N.mkisofs_opts
	exit 0; 
fi

# Now we do disk 1 ...
# couple of changes for 2.2.x bootdisks 27-dec-99 -- jwest

echo -n "-J -b boot/rescue.bin -c boot/boot.catalog boot1" > 1.mkisofs_opts

(cd $MIRROR/dists/$CODENAME1/main/disks-$ARCH/current/ ; \
	cp images-1.44/resc*.bin  $CDDIR/install ; \
	cp linux  $CDDIR/install ; \
	cp images-1.44/root.bin $CDDIR/install )

mkdir -p boot1/boot

cp $MIRROR/dists/$CODENAME1/main/disks-$ARCH/current/images-2.88/rescue.bin boot1/boot


#Extracting tools for disc 1

mkdir -p $CDDIR/install/dosutils

cp $MIRROR/dists/$CODENAME1/main/disks-$ARCH/current/dosutils/* $CDDIR/install/dosutils/


(echo "Tools for DOS :" ; \
	echo "lodlin/         load Linux kernel from DOS" ;\
	echo "rawrite2/       rawrite 2.0 : create disks from disk images (*.bin)"; \
	) |todos > $CDDIR/tools/README.tools


(echo "@ echo off" ; \
	echo "rem Flush any write-cached disk blocks before we leave DOS. " ; \
	echo "smartdrv /c" ; \
	echo "loadlin.exe linux root=/dev/ram ro initrd=root.bin" ; \
	) |todos > $CDDIR/install/boot.bat

