#!/bin/bash
#
# boot-alpha v 1.13 (c) Steve McIntyre <stevem@chiark.greenend.org.uk>
# and Loic Prylli <Loic.Prylli@ens-lyon.fr>
# Released under GPL 31 Mar 1999
# See the file COPYING for license details
# Released as part of the slink_cd package, not much use standalone
#
# Do install stuff for alpha, including making bootable CDs
#

set -e

N=$1
CDDIR=$2

cd $CDDIR/..

# Only disc 1 bootable

if [ $N != 1 ]; then 
	echo "-J" > $N.mkisofs_opts
	exit 0; 
fi

# Hack for bootable disks
mkdir -p boot1/boot

echo -n "-J boot1" > 1.mkisofs_opts

echo "extract aboot(bootlx) from sable set"
echo dump srmbootcode boot1/boot/bootlx |\
     debugfs $CDDIR/dists/$CODENAME/main/disks-$ARCH/current/sable/resc1440.bin
for subarch in avanti avanti-s xl xlt cabriolet eb66 eb66p eb64p eb164 pc164 \
      lx164 sx164 jensen noname takara mikasa mikasa-p noritake noritake-p alcor miata \
           sable sable-g  book1    ruffian; do      
 mkdir boot1/boot/$subarch
 echo "drive m: file=\"$CDDIR/dists/stable/main/disks-$ARCH/current/$subarch/resc1440.bin\"" > mtoolsrc.tmp
 echo "extracting stuff for $subarch"
 case $subarch in
          jensen|noritake*|mikasa-p|sable*|book1|miata-s|avanti-s|generic)
       echo dump linux boot1/boot/$subarch/linux |\
          debugfs $CDDIR/dists/$CODENAME/main/disks-$ARCH/current/$subarch/resc1440.bin
       ;;
       ruffian)
         MTOOLSRC=$CDDIR/../mtoolsrc.tmp mcopy m:linux m:milo m:ldmilo.exe boot1/boot/$subarch/.
   ;;         
       *)
         MTOOLSRC=$CDDIR/../mtoolsrc.tmp mcopy m:linux m:milo m:linload.exe boot1/boot/$subarch/.
   ;;
  esac
done

exit 0
