#!/bin/bash
#
# boot-mips64el - (C) 2017 Steve McIntyre <93sam@debian.org>
#
# You may copy, modify and distribute this under the terms of the GNU
# General Public License as published by the Free Software Foundation; 
# either version 2 of the License, or (at your option) any later version.
#
# $1 is the CD number
# $2 is the temporary CD build dir

. $BASEDIR/tools/boot/$DI_CODENAME/common.sh

set -e

N=$1
CDROOT=$2
if [ "$DI_WWW_HOME" = "default" ];then
    DI_WWW_HOME="https://d-i.debian.org/daily-images/mipsel/daily"
    try_di_image_cache
fi

# Mips64el is currently not bootable in stretch, so bail out here
echo "Mips64el booting disabled, check Sledge"
exit 0
