#!/bin/bash
#
# boot-mips
#
# $1 is the CD number
# $2 is the temporary CD build dir

# genisovh is used to make ISOs bootable on mips.

. $BASEDIR/tools/boot/$DI_CODENAME/common.sh

set -e

N=$1
CDDIR=$2
INSTALLDIR="install"
if [ "$DI_WWW_HOME" = "default" ];then
    DI_WWW_HOME="https://d-i.debian.org/daily-images/mips/daily/"
    try_di_image_cache
fi

add_mkisofs_opt $CDDIR/../$N.mkisofs_opts "-J -joliet-long"

# Only disk 1* bootable
if [ $N != 1 -a $N != 1_NONUS ]; then
	exit 0
fi

# Mips is currently not bootable directly from CD, and there's
# not a lot we can do about that. But add the needed files in the
# right place so that users can find them, at least:
#
# kernel(s)
# initramfs
# etc...
#
# The best wasy to find all the files is to parse d-i's MANIFEST file
# and work from there.
mkdir -p $CDDIR/$INSTALLDIR
cd $CDDIR/$INSTALLDIR

if [ ! "$DI_WWW_HOME" ];then
        if [ ! "$DI_DIR" ];then
           DI_DIR="$MIRROR/dists/$DI_DIST/main/installer-$ARCH/current/images"
        fi
    cp "$DI_DIR/MANIFEST" MANIFEST
else
    $WGET "$DI_WWW_HOME/MANIFEST" -O MANIFEST
fi

for image in $(awk '{print $1}' MANIFEST); do
    if [ ! -e "$image" ]; then
        dir=$(dirname $image)
        mkdir -p $dir
        if [ -n "$LOCAL"  -a -f "${LOCALDEBS:-$MIRROR}/dists/$DI_DIST/local/installer-$ARCH/current/images/$image" ]; then
            cp "${LOCALDEBS:-$MIRROR}/dists/$DI_DIST/local/installer-$ARCH/current/images/$image" "$image"
        elif [ ! "$DI_WWW_HOME" ];then
            if [ ! "$DI_DIR" ];then
                DI_DIR="$MIRROR/dists/$DI_DIST/main/installer-$ARCH/current/images"
            fi
            cp -a "$DI_DIR/$image" "$image"
        else
            $WGET --no-parent -r -nH --cut-dirs=3 "$DI_WWW_HOME/$image"
        fi
    fi
done

# Clean up in case we had to use $WGET :-(
find . -name 'index.html*' -delete

exit 0
