#!/bin/bash
#
# boot-mips64el - (C) 2017 Steve McIntyre <93sam@debian.org>
#
# You may copy, modify and distribute this under the terms of the GNU
# General Public License as published by the Free Software Foundation; 
# either version 2 of the License, or (at your option) any later version.
#
# $1 is the CD number
# $2 is the temporary CD build dir

. $BASEDIR/tools/boot/$DI_CODENAME/common.sh

set -e

N=$1
CDROOT=$2

# Exit if this is not CD#1/DVD#1
if [ $N != 1 ] ; then exit 0; fi

if [ "$DI_WWW_HOME" = "default" ];then
    DI_WWW_HOME="https://d-i.debian.org/daily-images/mips64el/daily"
    try_di_image_cache
fi

add_mkisofs_opt $CDDIR/../$N.mkisofs_opts "-J -joliet-long"

# This arch is currently not bootable directly from CD, and there's
# not a lot we can do about that. But add the needed files in the
# right place so that users can find them, at least
copy_arch_images
