#!/bin/bash
#
# boot-mips
#
# $1 is the CD number
# $2 is the temporary CD build dir

# genisovh is used to make ISOs bootable on mips.

. $BASEDIR/tools/boot/$DI_CODENAME/common.sh

set -e

N=$1
CDDIR=$2
INSTALLDIR="install"
if [ "$DI_WWW_HOME" = "default" ];then
    DI_WWW_HOME="https://d-i.debian.org/daily-images/mips/daily/"
    try_di_image_cache
fi

add_mkisofs_opt $CDDIR/../$N.mkisofs_opts "-J -joliet-long"

# Only disk 1* bootable
if [ $N != 1 ]; then
	exit 0
fi

# This arch is currently not bootable directly from CD, and there's
# not a lot we can do about that. But add the needed files in the
# right place so that users can find them, at least
copy_arch_images
