#!/bin/bash
#
# boot-powerpc version 0.7 (C)  Hartmut Koptein <koptein@debian.org>,
# PReP support (C)  Matt Porter <porter@debian.org>
#
# Released under GPL 1 Mar 1999
# See the file COPYING for license details
# Released as part of the debian_cd package, not much use standalone
#
# Do install stuff for powerpc, including making bootable CDs
#
# $1 is the CD number
# $2 is the temporary CD build dir

set -e

N=$1
CDROOT=$2

cd $CDROOT/..

# Only disk 1 bootable
if [ $N != 1 ]; then
	echo -n "--netatalk -j -hfs -probe -map $BASEDIR/data/hfs.map" \
	        > $N.mkisofs_opts
	exit 0
fi

echo -n "--netatalk -j -hfs -probe -map $BASEDIR/data/hfs.map" \
        > $N.mkisofs_opts
echo -n " -prep-boot install/prep/boot.bin" >> $N.mkisofs_opts

DISKSROOT="$MIRROR/dists/$CODENAME/main/disks-$ARCH/current"
INSTALLDIR="$CDROOT/install"

# Debian/PowerPC consits currently for three parts: CHRP, PMac and PReP
# Apus, MBX and BBox will hopefully follow
#
# -- We need a generic boot-loader --
# -- (We wish) --
#
cd $INSTALLDIR
# ---- auto-booting section -----
echo "Copying boot images to $CDROOT/install/boot for disc 1"
rm -fr boot
mkdir -p boot
for subarch in apus chrp common mbx powermac prep ; do
    mkdir boot/$subarch
    echo "extracting stuff for $subarch"
    case $subarch in
        apus)
                echo "need work for Apus"
        ;;
        chrp)
                echo "need work for CHRP"
        ;;
        common)
                echo "need work for common"
        ;;
        mbx)
                echo "need work for mbx"
        ;;
        powermac)
                #cp -p $BOOTDIR/cd.b $BOOTDIR/second.b boot/powermac
                #cp -p $BOOTDIR/second.b boot/powermac
                #cat - > boot/powermac/quik.conf << __EOF__
                #timeout=300
                #root=/dev/ram
                #image=!cd1
                #label=Linux
                #initrd=!cd5
                #__EOF__
                echo "need work for PowerMac"
        ;;
        prep)
		# PReP doesn't need an extra copy of the boot image
		# The -B parameter to mkhybrid points directly to our
		# PReP bootable image in /install/prep/boot.bin
		# We put a symlink here for now for uniformity.
                ln -s ../../prep/boot.bin boot/prep/
        ;;
    esac
done

#-------------- Install paths -------------------------------
# $DISKSROOT  == dists/potato/main/disks-powerpc/current/
# $INSTALLDIR == install/
#
# The layout has changed. Images are now in $SUBARCH/images-1.44
#

cd $INSTALLDIR

# Section for the base, rescue and drivers into the /install/
# area on the cd.

#--------------- APUS - Stuff -------------------------------
#echo Installing APUS files
mkdir apus
cp $DISKSROOT/apus/linux apus
cp $DISKSROOT/apus/images-1.44/root.bin apus
cp $DISKSROOT/apus/images-1.44/rescue.bin apus

#--------------- CHRP - Stuff -------------------------------
echo Installing CHRP files
mkdir chrp
cp $DISKSROOT/chrp/linux chrp
cp $DISKSROOT/chrp/images-1.44/root.bin chrp
cp $DISKSROOT/chrp/images-1.44/rescue.bin chrp

#-------------- Common - Stuff ------------------------------
#echo Installing Common files
#mkdir common
#cp $DISKSROOT/common/linux common
#cp $DISKSROOT/common/images-1.44/root.bin common
#cp $DISKSROOT/common/images-1.44/rescue.bin common

#---------------- MBX - Stuff -------------------------------
#echo Installing MBX files
#mkdir mbx
#cp $DISKSROOT/mbx/linux mbx
#cp $DISKSROOT/mbx/images-1.44/root.bin mbx
#cp $DISKSROOT/mbx/images-1.44/rescue.bin mbx

#--------------- PMac - Stuff -------------------------------
echo Installing Power-Macintosh files
mkdir powermac
cp $DISKSROOT/powermac/linux powermac
cp $DISKSROOT/powermac/images-1.44/root.bin powermac
cp $DISKSROOT/powermac/images-1.44/rescue.bin powermac

#--------------- PReP - Stuff -------------------------------
echo Installing PReP files
mkdir prep
cp $DISKSROOT/prep/linux prep
cp $DISKSROOT/prep/images-1.44/boot.bin prep
cp $DISKSROOT/prep/images-1.44/root.bin prep
cp $DISKSROOT/prep/images-1.44/rescue.bin prep

#=============== fix a few things up... =====================
echo Installing PowerPC FAQ and tools
#mkdir common
#mv basecont.txt.info common
#mv ../README.info ../README.powerpc.info
#cp ../README.1ST.info ../README.multicd.info

