#!/bin/sh

# This is a little shell script that will launch apt-get in dry-run mode
# to find all the dependencies of a specific package

# There's not set -e here because this script may fail !
# Apt doesn't always work ... 
# set -e

# Get the configuration information if necessary
if [ -z "$CODENAME" -o -z "$ARCH" -o -z "$APTTMP" ]; then
	if [ -e CONF.sh ]; then
		source CONF.sh
	else
		echo "Please set the good environment variables before "
		echo "launching this program ..."
		echo "Current values are :"
		echo "CODENAME=$CODENAME"
		echo "ARCH=$ARCH"
		echo "APTTMP=$APTTMP"
	fi
fi

options=" -o Dir::State::status=$APTTMP/$CODENAME-$ARCH/status \
          -o Dir::State=$APTTMP/$CODENAME-$ARCH/apt-state/ \
	  -o Dir::Cache=$APTTMP/$CODENAME-$ARCH/apt-cache/ \
	  -o Dir::Etc=$APTTMP/$CODENAME-$ARCH/apt/ \
	  -o APT::Architecture=$ARCH "

if [ -n "$NONFREE" -o -n "$EXTRANONFREE" ]; then
	sections="main contrib non-free"
else
	sections="main contrib"
fi

# Check for the necessary dirs and files ...
if [ ! -d "$APTTMP/$CODENAME-$ARCH/apt-state/lists/partial" ]; then
	mkdir -p "$APTTMP/$CODENAME-$ARCH/apt-state/lists/partial"
fi
if [ ! -d "$APTTMP/$CODENAME-$ARCH/apt-cache/archives/partial" ]; then
	mkdir -p "$APTTMP/$CODENAME-$ARCH/apt-cache/archives/partial"
fi
if [ ! -d "$APTTMP/$CODENAME-$ARCH/apt" ]; then
	mkdir -p "$APTTMP/$CODENAME-$ARCH/apt"
fi
if [ ! -e "$APTTMP/$CODENAME-$ARCH/apt/sources.list" ]; then
	# Generating a correct sources.list file
	echo "deb file:$MIRROR $CODENAME $sections" \
	> $APTTMP/$CODENAME-$ARCH/apt/sources.list
	if [ -n "$NONUS" ]; then
	  # Slink used the old paths
	  if [ "$CODENAME" = "slink" ]; then
	     echo "deb file:$NONUS $CODENAME non-US" \
	     >> $APTTMP/$CODENAME-$ARCH/apt/sources.list
	  else
	     echo "deb file:$NONUS $CODENAME/non-US $sections" \
	     >> $APTTMP/$CODENAME-$ARCH/apt/sources.list
	  fi
	fi
	# Local packages ...
	if [ -n "$LOCAL" ]; then
	  echo "deb file:$MIRROR $CODENAME local" \
	  >> $APTTMP/$CODENAME-$ARCH/apt/sources.list
	fi
fi

temp=$APTTMP/$CODENAME-$ARCH/temp.apt-selection

# Launch the command
if [ "$1" = "update" -o "$1" = "check" ]; then
	apt-get $options $@
	exit $?
elif [ "$1" = "cache" ]; then
	shift
	apt-cache $options $@
	exit $?
elif [ "$1" = "deselected" ]; then
	shift
	apt-get $options -s $@ > $temp
	num=$?
	#if [ $num -ne 0 ]; then 
	    #echo ": Param: apt-selection deselected $@" >&2; 
	    #exit $num;  
	#fi
	perl -ne 'print "$1\n" if /^Remv (\S+)\s*(?:\[|$)/' $temp | sort
elif [ "$1" = "selected" ]; then
	shift
	apt-get $options -s $@ > $temp 
	num=$?
	#if [ $num -ne 0 ]; then 
	#    echo "ERROR: Param: apt-selection selected $@" >&2; 
	#    exit $num;  
	#fi
	perl -ne 'print "$1\n" if /^Inst (\S+)\s*(?:\[|$)/' $temp | sort
else
	apt-get $options -s $@
	exit $?
fi

