#!/bin/sh

# Generate a list of packages required for debian-installer
# This script makes use of the following variables that need to be preset:
# MIRROR, CODENAME

DATE=`date`
cat > debian-installer+kernel << EOF
/* These files + the ones needed by debootstrap are the ones needed for
 * debian-installer to be able to complete the installation of the base.
 * at least at this pre-sarge days.
 *
 * This list can be generated with the command:
 * ../tools/generate_di+k_list
 *
 * Last update: $DATE
 */

#include <debian-installer>
discover
eject
grub
locales
lvm10
aptitude
jfbterm
unifont
#ifdef ARCH_i386
EOF

/bin/sed -n 's/Package: \(kernel-image-2.4.*-386\)$/\1/p' \
  $MIRROR/dists/$CODENAME/main/binary-i386/Packages|/usr/bin/tail -n 1 \
  >> debian-installer+kernel
/bin/sed -n 's/Package: \(kernel-pcmcia-modules-2.4.*-386\)$/\1/p' \
  $MIRROR/dists/$CODENAME/main/binary-i386/Packages|/usr/bin/tail -n 1 \
  >> debian-installer+kernel

cat >> debian-installer+kernel << EOF
#endif
#ifdef ARCH_alpha
EOF

/bin/sed -n 's/Package: \(kernel-image-.*\)$/\1/p' \
  $MIRROR/dists/$CODENAME/main/binary-alpha/Packages|grep -v 2.4.21 \
  >> debian-installer+kernel

cat >> debian-installer+kernel << EOF
#endif
#ifdef ARCH_ia64
EOF

/bin/sed -n 's/Package: \(kernel-image-.*\)$/\1/p' \
  $MIRROR/dists/$CODENAME/main/binary-ia64/Packages |tail -n 4 \
  >> debian-installer+kernel

cat >> debian-installer+kernel << EOF
#endif
#ifdef ARCH_powerpc
EOF

#This is just temporary, they are going to change it all for 2.4.22
/bin/sed -n 's/Package: \(kernel-image-.*-powerpc.*\)$/\1/p' \
  $MIRROR/dists/$CODENAME/main/binary-powerpc/Packages |tail -n 2 \
  >> debian-installer+kernel

cat >> debian-installer+kernel << EOF
#endif

EOF
