#!/bin/sh

set -e

APT=$BASEDIR/tools/apt-selection

# include all the education packages except education-development
$APT list 'education-*' 2>/dev/null | cut -d '/' -f1 | grep -v education-development > $1
