#!/bin/sh

# Generate a list of packages required for debian-installer
# This script makes use of the following variables that need to be preset:
# MIRROR, CODENAME

DATE=`date`
cat > debian-installer+kernel << EOF
/* These files + the ones needed by debootstrap are the ones needed for
 * debian-installer to be able to complete the installation of the base.
 * at least at this pre-sarge days.
 *
 * This list can be generated with the command:
 * ../tools/generate_di+k_list
 *
 * Last update: $DATE
 */

#include <debian-installer>
eject
locales
lvm10
aptitude
jfbterm
unifont
hotplug
iso-codes
console-cyrillic
console-terminus
pcmcia-cs
wireless-tools
xfsprogs
reiserfsprogs
#ifdef ARCH_i386
discover
grub
lilo
EOF

/bin/sed -n 's/Package: \(kernel-image-2.4.*-386\)$/\1/p' \
  $MIRROR/dists/$CODENAME/main/binary-i386/Packages|/usr/bin/tail -n 1 \
  >> debian-installer+kernel
/bin/sed -n 's/Package: \(kernel-pcmcia-modules-2.4.*-386\)$/\1/p' \
  $MIRROR/dists/$CODENAME/main/binary-i386/Packages|/usr/bin/tail -n 1 \
  >> debian-installer+kernel
/bin/sed -n 's/Package: \(kernel-image-2.6.*-386\)$/\1/p' \
  $MIRROR/dists/$CODENAME/main/binary-i386/Packages|/usr/bin/tail -n 1 \
  >> debian-installer+kernel

cat >> debian-installer+kernel << EOF
#endif
#ifdef ARCH_alpha
discover
EOF

/bin/sed -n 's/Package: \(kernel-image-.*\)$/\1/p' \
  $MIRROR/dists/$CODENAME/main/binary-alpha/Packages|grep -v 2.4.21 \
  >> debian-installer+kernel

cat >> debian-installer+kernel << EOF
#endif
#ifdef ARCH_hppa
discover
EOF

/bin/sed -n 's/Package: \(kernel-image-.*\)$/\1/p' \
  $MIRROR/dists/$CODENAME/main/binary-hppa/Packages|tail -n4 \
  >> debian-installer+kernel

cat >> debian-installer+kernel << EOF
#endif
#ifdef ARCH_ia64
discover
initrd-tools
EOF

/bin/sed -n 's/Package: \(kernel-image-.*\)$/\1/p' \
  $MIRROR/dists/$CODENAME/main/binary-ia64/Packages |tail -n 4 \
  >> debian-installer+kernel

cat >> debian-installer+kernel << EOF
#endif
#ifdef ARCH_mips
arcboot
EOF

# Only include mips kernels that d-i base-installer installs.
for subarch in r4k-ip22 r5k-ip22; do
	sed -n 's/Package: \(kernel-image-.*-.*\)$/\1/p' \
		$MIRROR/dists/$CODENAME/main/binary-mips/Packages \
		| grep -- "-$subarch$" | sort -n | tail -n 1 \
                >> debian-installer+kernel
done

cat >> debian-installer+kernel << EOF
#endif
#ifdef ARCH_mipsel
EOF

# Only include mipsel kernels that d-i base-installer installs.
for subarch in r3k-kn02 r4k-kn04; do
	sed -n 's/Package: \(kernel-image-.*-.*\)$/\1/p' \
		$MIRROR/dists/$CODENAME/main/binary-mipsel/Packages \
		| grep -- "-$subarch$" | sort -n | tail -n 1 \
                >> debian-installer+kernel
done

cat >> debian-installer+kernel << EOF
#endif
#ifdef ARCH_powerpc
discover
EOF

# Only include powerpc kernels that d-i base-installer installs.
for subarch in powerpc-pmac powerpc-small-pmac powerpc-prep powerpc-chrp \
               powerpc-chrp-rs6k apus; do
	sed -n 's/Package: \(kernel-image-.*-.*\)$/\1/p' \
		$MIRROR/dists/$CODENAME/main/binary-powerpc/Packages \
		| grep -- "-$subarch$" | sort -n | tail -n 1 \
                >> debian-installer+kernel
done

cat >> debian-installer+kernel << EOF
#endif
#ifdef ARCH_sparc
discover
EOF

/bin/sed -n 's/Package: \(kernel-image-.*-sparc.*\)$/\1/p' \
  $MIRROR/dists/$CODENAME/main/binary-sparc/Packages \
  >> debian-installer+kernel

cat >> debian-installer+kernel << EOF
#endif
#ifdef ARCH_m68k
EOF

# Get all the 2.2 kernels
/bin/sed -n 's/Package: \(kernel-image-2.2.*\)$/\1/p' \
  $MIRROR/dists/$CODENAME/main/binary-m68k/Packages | tail -n 6 \
  >> debian-installer+kernel
# Get the latest 2.4 kernel for amiga
/bin/sed -n 's/Package: \(kernel-image-2.4.*-amiga\)$/\1/p' \
  $MIRROR/dists/$CODENAME/main/binary-m68k/Packages | tail -n 1 \
  >> debian-installer+kernel

cat >> debian-installer+kernel << EOF
#endif
EOF
